steps:

  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
            'us-west1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA', 
            '.']

  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
            'us-west1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
            'us-west1-docker.pkg.dev/$PROJECT_ID/backend-nginx/nginx:$COMMIT_SHA', 
            './nginx']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
          'us-west1-docker.pkg.dev/$PROJECT_ID/backend-nginx/nginx:$COMMIT_SHA']

  #SSH to GCE instance
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - >-
        gcloud compute ssh root@dev-backend --zone=us-west1-a
        --command="
        docker-compose down -v &&
        docker images | xargs docker rmi &&
        IMAGE_1=us-west1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA IMAGE_2=us-west1-docker.pkg.dev/$PROJECT_ID/backend-nginx/nginx:$COMMIT_SHA docker-compose up -d "

    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
