version: "3"
services:

  app:
    restart: always
    command: ./startup.sh
    build:
      context: .
      dockerfile: Dockerfile
    image: us-west1-docker.pkg.dev/freightmonster-dev/backend/backend:v1
    container_name: backend
    expose:
      - "8000"
    volumes:
      - static_volume:/code/static
    hostname: app

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: us-west1-docker.pkg.dev/freightmonster-dev/backend-nginx/backend-nginx:v1
    volumes:
      - static_volume:/code/static
    ports:
      - "80:80" 
    depends_on:
      - app
      
volumes:
  static_volume: