# Generated by Django 4.1.7 on 2023-03-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="owner",
            new_name="uploaded_by",
        ),
    ]
