# Generated by Django 4.1.7 on 2023-03-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        (
            "shipment",
            "0002_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
        ("document", "0003_rename_owner_uploadedfile_uploaded_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_offer",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("carrier_offer", models.DecimalField(decimal_places=2, max_digits=12)),
                ("length", models.DecimalField(decimal_places=2, max_digits=12)),
                ("width", models.DecimalField(decimal_places=2, max_digits=12)),
                ("height", models.DecimalField(decimal_places=2, max_digits=12)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.IntegerField(default=1)),
                ("commodity", models.CharField(max_length=255)),
                ("trailer_type", models.CharField(max_length=100)),
                ("pick_up_date", models.DateField()),
                ("drop_off_date", models.DateField()),
                ("issuing_date", models.DateTimeField(auto_now_add=True)),
                (
                    "goods_info",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=3,
                    ),
                ),
                (
                    "load_type",
                    models.CharField(
                        choices=[("LTL", "LTL"), ("FTL", "FTL")], max_length=3
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.broker",
                    ),
                ),
                (
                    "broker_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_company",
                        to="authentication.company",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.carrier",
                    ),
                ),
                (
                    "carrier_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrier_company",
                        to="authentication.company",
                    ),
                ),
                (
                    "consignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_consignee",
                        to="authentication.shipmentparty",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_customer",
                        to="authentication.shipmentparty",
                    ),
                ),
                (
                    "customer_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_company",
                        to="authentication.company",
                    ),
                ),
                (
                    "drop_off_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_drop_off",
                        to="shipment.facility",
                    ),
                ),
                (
                    "pick_up_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_pick_up",
                        to="shipment.facility",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipment.shipment",
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_shipper",
                        to="authentication.shipmentparty",
                    ),
                ),
            ],
        ),
    ]
