# Generated by Django 4.1.7 on 2023-03-14 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_remove_uploadedfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="size",
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
