# Generated by Django 4.1.7 on 2023-03-20 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0007_alter_uploadedfile_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finalagreement",
            old_name="drop_off_date",
            new_name="dropoff_date",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="pick_up_date",
            new_name="pickup_date",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="broker",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="broker_company",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="carrier_company",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="consignee",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="customer_company",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="drop_off_location",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="issuing_date",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="pick_up_location",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="shipment",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="shipper",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="trailer_type",
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_company_address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_company_fax_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_company_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_email",
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_full_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_phone_number",
            field=models.CharField(default=None, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_company_address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_company_fax_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_company_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_email",
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_full_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_phone_number",
            field=models.CharField(default=None, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_uuid",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                validators=[django.core.validators.MinLengthValidator(36)],
            ),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="consignee_facility_address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="consignee_facility_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="consignee_full_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="consignee_phone_number",
            field=models.CharField(default=None, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="consignee_username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_company_address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_company_fax_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_company_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_email",
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_full_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_phone_number",
            field=models.CharField(default=None, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_uuid",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                validators=[django.core.validators.MinLengthValidator(36)],
            ),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="did_carrier_agree",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="did_customer_agree",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="shipper_facility_address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="shipper_facility_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="shipper_full_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="shipper_phone_number",
            field=models.CharField(default=None, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="shipper_username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_offer",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_offer",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="load_type",
            field=models.CharField(
                choices=[("LTL", "LTL"), ("FTL", "FTL")], default="FTL", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
