# Generated by Django 4.1.7 on 2023-03-20 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_rename_drop_off_date_finalagreement_dropoff_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalagreement",
            name="generated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="load_id",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
