# Generated by Django 4.1.7 on 2023-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document",
            "0009_finalagreement_generated_at_finalagreement_load_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_company_address",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_company_fax_number",
            field=models.CharField(
                blank=True, editable=False, max_length=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_company_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_email",
            field=models.EmailField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_full_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_phone_number",
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="broker_username",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_company_address",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_company_fax_number",
            field=models.CharField(
                blank=True, editable=False, max_length=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_company_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_email",
            field=models.EmailField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_full_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_offer",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_phone_number",
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_username",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="carrier_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="commodity",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="consignee_facility_address",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="consignee_facility_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="consignee_full_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="consignee_phone_number",
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="consignee_username",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_company_address",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_company_fax_number",
            field=models.CharField(
                blank=True, editable=False, max_length=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_company_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_email",
            field=models.EmailField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_full_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_offer",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_phone_number",
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_username",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="customer_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="dropoff_date",
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="goods_info",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="height",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="length",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="load_id",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="load_type",
            field=models.CharField(
                choices=[("LTL", "LTL"), ("FTL", "FTL")],
                default="FTL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="pickup_date",
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="shipper_facility_address",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="shipper_facility_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="shipper_full_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="shipper_phone_number",
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="shipper_username",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="weight",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name="finalagreement",
            name="width",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
