# Generated by Django 4.1.7 on 2023-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0010_alter_finalagreement_broker_company_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_company_address",
            new_name="broker_billing_address",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_company_name",
            new_name="broker_billing_name",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="carrier_company_address",
            new_name="carrier_billing_address",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="carrier_company_name",
            new_name="carrier_billing_name",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="customer_company_address",
            new_name="customer_billing_address",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="customer_company_name",
            new_name="customer_billing_name",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="broker_company_fax_number",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="carrier_company_fax_number",
        ),
        migrations.RemoveField(
            model_name="finalagreement",
            name="customer_company_fax_number",
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="broker_billing_phone_number",
            field=models.CharField(default=None, editable=False, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="carrier_billing_phone_number",
            field=models.CharField(default=None, editable=False, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="customer_billing_phone_number",
            field=models.CharField(default=None, editable=False, max_length=18),
            preserve_default=False,
        ),
    ]
