# Generated by Django 4.1.7 on 2023-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document",
            "0011_rename_broker_company_address_finalagreement_broker_billing_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="finalagreement",
            name="equipment",
            field=models.CharField(default="Flat Bed", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="load_name",
            field=models.CharField(
                default="L-SJ23K", editable=False, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalagreement",
            name="shipment_name",
            field=models.CharField(
                default="SH-KJB56", editable=False, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
