# Generated by Django 4.1.7 on 2023-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0013_alter_finalagreement_shipment_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_billing_address",
            new_name="dispatcher_billing_address",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_billing_name",
            new_name="dispatcher_billing_name",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_billing_phone_number",
            new_name="dispatcher_billing_phone_number",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_email",
            new_name="dispatcher_email",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_full_name",
            new_name="dispatcher_full_name",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_phone_number",
            new_name="dispatcher_phone_number",
        ),
        migrations.RenameField(
            model_name="finalagreement",
            old_name="broker_username",
            new_name="dispatcher_username",
        ),
    ]
