AWAITING_DISPATCHER = "Awaiting Dispatcher"
AWAITING_CARRIER = "Awaiting Carrier"
READY_FOR_PICKUP = "Ready For Pickup"
ASSIGNING_CARRIER = "Assigning Carrier"
AWAITING_CUSTOMER = "Awaiting Customer"
IN_TRANSIT = "In Transit"