# Generated by Django 4.1.5 on 2023-01-26 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AlterField(
            model_name="load",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 26))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
