# Generated by Django 4.1.5 on 2023-03-07 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 3, 7))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
