# Generated by Django 4.1 on 2022-10-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0002_alter_facility_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="owner",
        ),
    ]
