# Generated by Django 4.1 on 2023-01-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        (
            "shipment",
            "0002_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shipment",
            unique_together={("created_by", "name")},
        ),
    ]
