# Generated by Django 4.1.5 on 2023-01-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment",
            "0002_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
