# Generated by Django 4.1.7 on 2023-03-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment",
            "0003_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
    ]
