# Generated by Django 4.1.5 on 2023-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0003_alter_shipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Awaiting shipper", "Awaiting shipper"),
                    ("Assigning carrier", "Assigning carrier"),
                    ("Awaiting carrier", "Awaiting carrier"),
                    ("Ready For Pick Up", "Ready For Pick Up"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
    ]
