# Generated by Django 4.1 on 2023-01-05 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("shipment", "0003_alter_shipment_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentAdmins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 5))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
        migrations.AddField(
            model_name="shipmentadmins",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.appuser"
            ),
        ),
        migrations.AddField(
            model_name="shipmentadmins",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shipment.shipment"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shipmentadmins",
            unique_together={("shipment", "admin")},
        ),
    ]
