# Generated by Django 4.1 on 2022-10-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_appuser_is_deleted"),
        ("shipment", "0004_facility_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="authentication.shipmentparty",
            ),
        ),
    ]
