# Generated by Django 4.1.7 on 2023-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment",
            "0004_remove_load_pick_up_date should be greater than or equal today's date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="equipment",
            field=models.CharField(default="Flat Bed", max_length=255),
            preserve_default=False,
        ),
    ]
