# Generated by Django 4.1.2 on 2023-01-06 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("shipment", "0004_shipmentadmins_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShipmentAdmins",
            new_name="ShipmentAdmin",
        ),
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 6))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
