# Generated by Django 4.1.5 on 2023-01-27 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0004_alter_load_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AlterField(
            model_name="load",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Awaiting Customer", "Awaiting Customer"),
                    ("Assigning Carrier", "Assigning Carrier"),
                    ("Awaiting Carrier", "Awaiting Carrier"),
                    ("Awaiting Broker", "Awaiting Broker"),
                    ("Ready For Pick Up", "Ready For Pick Up"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 27))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
