# Generated by Django 4.1.5 on 2023-01-30 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment",
            "0005_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="status",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 30))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
