# Generated by Django 4.1 on 2023-01-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0005_rename_shipmentadmins_shipmentadmin_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.RenameField(
            model_name="load",
            old_name="depth",
            new_name="length",
        ),
        migrations.AlterField(
            model_name="load",
            name="goods_info",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 9))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
