# Generated by Django 4.1 on 2022-10-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0005_alter_facility_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("max_height", models.FloatField()),
                ("max_length", models.FloatField()),
                ("max_width", models.FloatField()),
            ],
        ),
    ]
