# Generated by Django 4.1.7 on 2023-04-19 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0005_load_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
