# Generated by Django 4.1 on 2023-01-24 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        (
            "shipment",
            "0006_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AlterUniqueTogether(
            name="offer",
            unique_together={("party_1", "party_2", "load")},
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2023, 1, 24))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
