# Generated by Django 4.1.7 on 2023-05-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_address_created_by"),
        ("shipment", "0007_offer_created_at_offer_to"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offer",
            unique_together={("party_1", "party_2", "load", "to")},
        ),
    ]
