# Generated by Django 4.1 on 2022-11-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0007_load"),
    ]

    operations = [
        migrations.RenameField(
            model_name="load",
            old_name="creator",
            new_name="created_by",
        ),
    ]
