# Generated by Django 4.1.7 on 2023-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0008_alter_offer_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="load",
            old_name="broker",
            new_name="dispatcher",
        ),
        migrations.AlterField(
            model_name="load",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Awaiting Customer", "Awaiting Customer"),
                    ("Assigning Carrier", "Assigning Carrier"),
                    ("Awaiting Carrier", "Awaiting Carrier"),
                    ("Awaiting Dispatcher", "Awaiting Dispatcher"),
                    ("Ready For Pick Up", "Ready For Pick Up"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
    ]
