# Generated by Django 4.1 on 2022-11-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0008_rename_creator_load_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="load",
            old_name="created_by",
            new_name="creator",
        ),
    ]
