# Generated by Django 4.1.10 on 2023-08-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0009_rename_broker_load_dispatcher_alter_load_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Awaiting Customer", "Awaiting Customer"),
                    ("Assigning Carrier", "Assigning Carrier"),
                    ("Awaiting Carrier", "Awaiting Carrier"),
                    ("Awaiting Dispatcher", "Awaiting Dispatcher"),
                    ("Ready For Pickup", "Ready For Pickup"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
    ]
