# Generated by Django 4.2.5 on 2023-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0010_alter_load_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="actual_delivery_date",
            field=models.DateField(null=True),
        ),
    ]
