# Generated by Django 4.2.5 on 2023-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0013_rename_info_claim_description_of_loss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="commodity_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
