# Generated by Django 4.1 on 2022-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0013_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="depth",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="load",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="load",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="load",
            name="weight",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="load",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
