# Generated by Django 4.2.5 on 2023-12-14 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0015_alter_claim_claimant_alter_claim_claimed_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claim",
            old_name="load_id",
            new_name="load",
        ),
    ]
