# Generated by Django 4.1 on 2022-11-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0006_alter_appuser_user_alter_broker_app_user_and_more"),
        ("shipment", "0015_alter_contact_app_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="app_user",
        ),
        migrations.AddField(
            model_name="contact",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="authentication.appuser",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.shipmentparty",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.broker",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="carrier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.carrier",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="consignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consignee",
                to="authentication.shipmentparty",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.appuser"
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination",
                to="shipment.facility",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="pick_up_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pick_up",
                to="shipment.facility",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="shipper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipper",
                to="authentication.shipmentparty",
            ),
        ),
    ]
