# Generated by Django 4.2.5 on 2023-12-18 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0016_rename_load_id_claim_load"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="claimant_role",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="claimed_on_role",
        ),
    ]
