# Generated by Django 4.1 on 2022-11-30 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0006_alter_appuser_user_alter_broker_app_user_and_more"),
        ("shipment", "0016_remove_contact_app_user_contact_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="goods_info",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="load",
            name="load_type",
            field=models.CharField(
                choices=[("LTL", "LTL"), ("FTL", "FTL")], default="FTL", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Information Recieved", "Information Recieved"),
                    ("Confirmed", "Confirmed"),
                    ("Signed", "Signed"),
                    ("Ready For Pick Up", "Ready For Pick Up"),
                    ("Picked Up", "Picked Up"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("origin", "contact")},
        ),
    ]
