# Generated by Django 4.1 on 2022-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0017_load_goods_info_load_load_type_alter_load_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
