# Generated by Django 4.2.5 on 2023-12-19 17:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0017_remove_claim_claimant_role_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claim",
            old_name="Date_of_loss",
            new_name="date_of_loss",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="evidences",
        ),
        migrations.AddField(
            model_name="claim",
            name="supporting_docs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=[""], size=None
            ),
            preserve_default=False,
        ),
    ]
