# Generated by Django 4.2.5 on 2023-12-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0018_rename_date_of_loss_claim_date_of_loss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[("open", "open"), ("resolved", "resolved")], max_length=11
            ),
        ),
    ]
