# Generated by Django 4.1.2 on 2022-12-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0019_alter_facility_owner_alter_load_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="extra_info",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
