# Generated by Django 4.2.5 on 2024-01-02 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0019_alter_claim_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="claimed_on",
        ),
    ]
