# Generated by Django 4.2.5 on 2024-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0020_remove_claim_claimed_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="commodity_description",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="commodity_type",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="type_of_loss",
        ),
        migrations.AlterField(
            model_name="claim",
            name="description_of_loss",
            field=models.TextField(blank=True),
        ),
    ]
