# Generated by Django 4.2.5 on 2024-01-15 15:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0020_alter_company_scac"),
        ("shipment", "0021_remove_claim_commodity_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "supporting_docs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shipment.claim"
                    ),
                ),
                (
                    "claimer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.appuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("claim", "claimer")},
            },
        ),
        migrations.DeleteModel(
            name="ClaimMessage",
        ),
    ]
