# Generated by Django 4.1 on 2022-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0021_alter_load_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="depth",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="load",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="weight",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
