# Generated by Django 4.1 on 2022-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment",
            "0022_alter_load_depth_alter_load_height_alter_load_name_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("delivery_date__gt", models.F("pick_up_date"))),
                name="check_delivery_date",
            ),
        ),
    ]
