# Generated by Django 4.1 on 2022-12-08 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0023_load_check_delivery_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="check_delivery_date",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("delivery_date__gt", models.F("pick_up_date"))),
                name="delivery_date_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2022, 12, 8))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
