# Generated by Django 4.2.5 on 2024-01-16 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0023_claimnote_delete_claimnotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimnote",
            name="supporting_docs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
    ]
