# Generated by Django 4.1 on 2022-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0024_remove_load_check_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pick_up_location", models.F("destination")), _negated=True
                ),
                name="pick up location and drop off location cannot be equal",
            ),
        ),
    ]
