# Generated by Django 4.1 on 2022-12-09 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment",
            "0025_load_pick up location and drop off location cannot be equal",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AlterField(
            model_name="load",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Signed", "Signed"),
                    ("Ready For Pick Up", "Ready For Pick Up"),
                    ("Picked Up", "Picked Up"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2022, 12, 9))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
    ]
