# Generated by Django 4.1 on 2022-12-15 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_appuser_user_alter_broker_app_user_and_more"),
        (
            "shipment",
            "0026_remove_load_pick_up_date should be greater than or equal today's date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="load",
            name="pick_up_date should be greater than or equal today's date",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(("pick_up_date__gte", datetime.date(2022, 12, 15))),
                name="pick_up_date should be greater than or equal today's date",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidder",
                to="authentication.appuser",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="authentication.appuser",
            ),
        ),
    ]
