# Generated by Django 4.2.5 on 2024-01-19 17:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0028_alter_loadnote_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadnote",
            name="attachments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
