# Generated by Django 4.2.5 on 2024-01-19 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0029_alter_loadnote_attachments"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loadnote",
            unique_together=set(),
        ),
    ]
