# Generated by Django 4.2.5 on 2024-01-19 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0030_alter_loadnote_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadnote",
            name="attachments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="loadnote",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
