# Generated by Django 4.2.5 on 2024-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0031_alter_loadnote_attachments_alter_loadnote_message"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loadnote",
            name="message_or_attachments_not_default",
        ),
        migrations.AddField(
            model_name="loadnote",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is Deleted"),
        ),
        migrations.AlterField(
            model_name="loadnote",
            name="message",
            field=models.TextField(),
        ),
    ]
