# Generated by Django 4.2.5 on 2024-01-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0031_alter_loadnote_attachments_alter_loadnote_message"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loadnote",
            name="message_or_attachments_not_default",
        ),
        migrations.AddField(
            model_name="loadnote",
            name="is_created",
            field=models.BooleanField(default=False, verbose_name="is created"),
        ),
        migrations.AddConstraint(
            model_name="loadnote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("message", ""), _negated=True),
                        models.Q(("attachments__len", 0), _negated=True),
                        _connector="OR",
                    ),
                    ("is_created", False),
                ),
                name="message_or_attachments_not_default",
            ),
        ),
    ]
