# Generated by Django 4.2.5 on 2024-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0033_alter_facility_options_facility_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="equipment",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
