# Generated by Django 4.2.5 on 2024-02-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0021_alter_address_options_address_created_at_and_more"),
        ("shipment", "0034_alter_load_equipment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="pick up location and drop off location cannot be equal",
        ),
        migrations.AddField(
            model_name="load",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="load",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="load",
            name="actual_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="commodity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="load",
            name="consignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consignee",
                to="authentication.shipmentparty",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="authentication.shipmentparty",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="delivery_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination",
                to="shipment.facility",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="dispatcher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.dispatcher",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="goods_info",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="height",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="length",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="pick_up_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="pick_up_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pick_up",
                to="shipment.facility",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="shipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipment.shipment",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="shipper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipper",
                to="authentication.shipmentparty",
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="weight",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="width",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("pick_up_location", models.F("destination")), _negated=True
                    ),
                    ("pick_up_location", None),
                    _connector="OR",
                ),
                name="pick up location and drop off location cannot be equal",
            ),
        ),
    ]
