# Generated by Django 4.2.5 on 2024-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shipment",
            "0035_remove_load_pick_up_location_and_drop_off_location_cannot_be_equal_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="load",
            name="delivery_date_check",
        ),
        migrations.AddConstraint(
            model_name="load",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("delivery_date__gt", models.F("pick_up_date")),
                    ("delivery_date", None),
                    _connector="OR",
                ),
                name="delivery_date_check",
            ),
        ),
    ]
