# Generated by Django 4.2.5 on 2024-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0036_remove_load_delivery_date_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
