# Generated by Django 4.2.5 on 2024-01-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shipment",
            "0036_remove_loadnote_message_or_attachments_not_default_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loadnote",
            name="message_or_attachments_not_default",
        ),
        migrations.RemoveField(
            model_name="loadnote",
            name="is_created",
        ),
        migrations.AlterField(
            model_name="loadnote",
            name="message",
            field=models.TextField(),
        ),
    ]
