# Generated by Django 4.2.5 on 2024-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0037_alter_load_height_alter_load_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="commodity",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="load",
            name="equipment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="load",
            name="goods_info",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="load",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="length",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="load",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
