# Generated by Django 4.2.5 on 2024-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0038_alter_load_commodity_alter_load_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="length",
            field=models.DecimalField(decimal_places=2, default="", max_digits=12),
        ),
    ]
