# Generated by Django 4.2.5 on 2024-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0039_alter_load_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="length",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
