# Generated by Django 4.2.5 on 2024-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0040_alter_load_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="load",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
