# Generated by Django 4.2.5 on 2024-02-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0041_alter_load_height_alter_load_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="shipment",
            field=models.ForeignKey(
                default=54,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipment.shipment",
            ),
            preserve_default=False,
        ),
    ]
