# Generated by Django 4.2.5 on 2024-02-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0042_alter_load_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="shipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipment.shipment",
            ),
        ),
    ]
