# Generated by Django 4.2.5 on 2024-02-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0043_alter_load_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
