# Generated by Django 4.1.10 on 2023-09-06 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0012_company_admin_alter_appuser_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "personal_phone",
                    models.CharField(editable=False, max_length=18, unique=True),
                ),
                ("company_name", models.CharField(max_length=100, unique=True)),
                ("company_domain", models.CharField(max_length=150, unique=True)),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10"),
                            ("11-50", "11-50"),
                            ("51-100", "51-100"),
                            (">100", ">100"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "EIN",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(9)],
                    ),
                ),
                (
                    "company_fax_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("company_phone_number", models.CharField(max_length=18, unique=True)),
                ("sid_photo", models.CharField(max_length=255, unique=True)),
                ("personal_photo", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Denied", "Denied"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                (
                    "company_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.address",
                    ),
                ),
            ],
        ),
    ]
