# Generated by Django 4.2.5 on 2023-09-25 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="personal_phone",
            new_name="personal_phone_number",
        ),
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="handled_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="rejection_reason",
            field=models.TextField(default=""),
        ),
    ]
