# Generated by Django 4.2.5 on 2023-10-23 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0003_remove_ticket_company_address_ticket_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="insurance_expiration_date",
        ),
    ]
