# Generated by Django 4.2.5 on 2023-11-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_remove_ticket_insurance_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="company_fax_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
