# Generated by Django 4.2.5 on 2023-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0007_alter_ticket_scac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="EIN",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="insurance_policy_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="scac",
            field=models.CharField(default="", max_length=4),
        ),
    ]
