# Generated by Django 4.2.5 on 2024-02-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0008_alter_ticket_ein_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="EIN",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company_domain",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company_phone_number",
            field=models.CharField(default="", max_length=18),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-100", "51-100"),
                    (">100", ">100"),
                ],
                default="",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="insurance_policy_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="insurance_premium_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="insurance_provider",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="insurance_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="personal_photo",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="sid_photo",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="zip_code",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_name", ""), _negated=True),
                fields=("company_name",),
                name="company_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_domain", ""), _negated=True),
                fields=("company_domain",),
                name="company_domain_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("EIN", ""), _negated=True),
                fields=("EIN",),
                name="EIN_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_phone_number", ""), _negated=True),
                fields=("company_phone_number",),
                name="company_phone_number_unique",
            ),
        ),
    ]
