# Generated by Django 4.1.7 on 2023-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="fax_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
