# Generated by Django 4.1 on 2022-08-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="broker",
            old_name="user",
            new_name="app_user",
        ),
        migrations.RenameField(
            model_name="carrier",
            old_name="user",
            new_name="app_user",
        ),
        migrations.RenameField(
            model_name="shipmentparty",
            old_name="user",
            new_name="app_user",
        ),
    ]
