# Generated by Django 4.1.5 on 2023-03-07 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_companyemployee_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="EIN",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(9)],
            ),
        ),
        migrations.AlterField(
            model_name="usertax",
            name="TIN",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(9)],
            ),
        ),
    ]
