# Generated by Django 4.1 on 2022-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_user_broker_app_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
