# Generated by Django 4.1 on 2022-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_appuser_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="allowed_to_operate",
            field=models.BooleanField(default=False),
        ),
    ]
