# Generated by Django 4.1.7 on 2023-03-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_carrier_mc_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertax",
            name="address",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="fax_number",
            field=models.CharField(default="N/A", max_length=18),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(default=None, max_length=18),
            preserve_default=False,
        ),
    ]
