# Generated by Django 4.1.7 on 2023-05-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0004_usertax_address_alter_company_fax_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="building_number",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street",
        ),
        migrations.AddField(
            model_name="address",
            name="address",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="selected_role",
            field=models.CharField(
                choices=[
                    ("carrier", "carrier"),
                    ("broker", "broker"),
                    ("shipment party", "shipment party"),
                ],
                default="N/A",
                max_length=14,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("carrier", "carrier"),
                    ("broker", "broker"),
                    ("shipment party", "shipment party"),
                    ("broker-carrier", "broker-carrier"),
                    ("broker-shipment party", "broker-shipment party"),
                    ("carrier-shipment party", "carrier-shipment party"),
                    ("broker-carrier-shipment party", "broker-carrier-shipment party"),
                ],
                max_length=29,
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitee", models.EmailField(max_length=254)),
                ("token", models.UUIDField(editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
