# Generated by Django 4.1 on 2022-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_broker_allowed_to_operate_carrier_allowed_to_operate"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="allowed_to_operate",
            field=models.BooleanField(default=False),
        ),
    ]
