# Generated by Django 4.1 on 2022-11-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0005_carrier_allowed_to_operate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="broker",
            name="app_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.appuser"
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="app_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.appuser"
            ),
        ),
        migrations.AlterField(
            model_name="shipmentparty",
            name="app_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.appuser"
            ),
        ),
    ]
