# Generated by Django 4.1.7 on 2023-05-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_remove_address_building_number_remove_address_street_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="created_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.appuser",
            ),
            preserve_default=False,
        ),
    ]
