# Generated by Django 4.1.7 on 2023-06-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0007_rename_broker_dispatcher_alter_appuser_selected_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("carrier", "carrier"),
                    ("dispatcher", "dispatcher"),
                    ("shipment party", "shipment party"),
                    ("carrier-dispatcher", "carrier-dispatcher"),
                    ("dispatcher-shipment party", "dispatcher-shipment party"),
                    ("carrier-shipment party", "carrier-shipment party"),
                    (
                        "carrier-dispatcher-shipment party",
                        "carrier-dispatcher-shipment party",
                    ),
                ],
                max_length=33,
            ),
        ),
    ]
