# Generated by Django 4.1.7 on 2023-06-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_appuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
