# Generated by Django 4.1.7 on 2023-06-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_invitation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="token",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.appuser"
            ),
        ),
    ]
