# Generated by Django 4.1.7 on 2023-07-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_remove_invitation_token_alter_invitation_inviter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
