# Generated by Django 4.1.10 on 2023-09-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_delete_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="admin",
            field=models.OneToOneField(
                default=214,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.appuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("carrier", "carrier"),
                    ("dispatcher", "dispatcher"),
                    ("shipment party", "shipment party"),
                    ("carrier-dispatcher", "carrier-dispatcher"),
                    ("dispatcher-shipment party", "dispatcher-shipment party"),
                    ("carrier-shipment party", "carrier-shipment party"),
                    (
                        "carrier-dispatcher-shipment party",
                        "carrier-dispatcher-shipment party",
                    ),
                    ("manager", "manager"),
                ],
                max_length=33,
            ),
        ),
    ]
