# Generated by Django 4.2.5 on 2023-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0013_alter_address_created_by_alter_appuser_selected_role_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.CharField(default="x.com", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
