# Generated by Django 4.2.5 on 2023-11-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0016_alter_address_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-100", "51-100"),
                    (">100", ">100"),
                ],
                default="1-10",
                max_length=6,
            ),
        ),
    ]
