# Generated by Django 4.2.5 on 2023-11-29 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0017_company_company_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="scac",
            field=models.CharField(
                default="",
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
