# Generated by Django 4.2.5 on 2023-11-30 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0019_alter_company_scac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="scac",
            field=models.CharField(
                default="",
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
