# Generated by Django 4.2.5 on 2024-02-02 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0020_alter_company_scac"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
