# Generated by Django 4.2.5 on 2023-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="details",
            field=models.JSONField(),
        ),
    ]
