# Generated by Django 4.1.7 on 2023-07-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0011_delete_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_allowed", models.BooleanField(default=True)),
                (
                    "methods",
                    models.CharField(
                        choices=[("email", "email"), ("sms", "sms"), ("both", "both")],
                        default="email",
                        max_length=5,
                    ),
                ),
                ("add_as_contact", models.BooleanField(default=True)),
                ("add_to_load", models.BooleanField(default=True)),
                ("got_offer", models.BooleanField(default=True)),
                ("offer_updated", models.BooleanField(default=True)),
                ("add_as_shipment_admin", models.BooleanField(default=True)),
                ("load_to_ready_to_pickup", models.BooleanField(default=True)),
                ("load_to_in_transit", models.BooleanField(default=True)),
                ("load_to_delivered", models.BooleanField(default=True)),
                ("load_to_canceled", models.BooleanField(default=True)),
                ("RC_approved", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.appuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.appuser",
                    ),
                ),
            ],
        ),
    ]
