# Generated by Django 4.1.10 on 2023-08-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_delete_invitation"),
        (
            "notifications",
            "0002_rename_load_to_canceled_notificationsetting_load_status_changed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifier",
                to="authentication.appuser",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(
                default="https://dev.freightslayer.com/load-details/49"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notified",
                to="authentication.appuser",
            ),
        ),
    ]
