# Generated by Django 4.2.5 on 2023-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_sender_notification_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="manager_seen",
            field=models.BooleanField(default=False),
        ),
    ]
