# Generated by Django 4.2.5 on 2023-12-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notification_manager_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsetting",
            name="claim_created",
            field=models.BooleanField(default=True),
        ),
    ]
