# Generated by Django 4.2.5 on 2024-02-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
