# Generated by Django 4.2.5 on 2024-02-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0002_alter_invitation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invitations_resent_count",
            field=models.IntegerField(default=0),
        ),
    ]
