# Generated by Django 4.2.5 on 2024-02-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0003_invitation_invitations_resent_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="last_time_sent",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
