# Generated by Django 4.2.5 on 2023-10-20 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0016_alter_address_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                (
                    "policy_number",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("expiration_date", models.DateField()),
                ("premium_amount", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
        ),
    ]
